import { Dossier, DashboardStats, User, DossierStatus } from '@/types';

export const currentUser: User = {
  id: '1',
  name: 'Marie Dupont',
  email: 'marie.dupont@utility.fr',
  role: 'admin',
};

export const statusLabels: Record<DossierStatus, string> = {
  DRAFT: 'Brouillon',
  DOSSIER_COMPLETE: 'Dossier complet',
  TECHNICAL_REVIEW: 'Étude technique',
  WORKS_REQUIRED: 'Travaux requis',
  WORKS_VALIDATED: 'Travaux validés',
  CONTRACT_SENT: 'Contrat envoyé',
  CONTRACT_SIGNED: 'Contrat signé',
  METER_SCHEDULED: 'Installation planifiée',
  METER_INSTALLED: 'Compteur installé',
  INSTALLATION_REPORT_RECEIVED: 'PV reçu',
  CUSTOMER_VALIDATED: 'Client validé',
  SUBSCRIPTION_ACTIVE: 'Abonnement actif',
  REJECTED: 'Rejeté',
  CANCELLED: 'Annulé',
};

export const subscriptionTypeLabels: Record<string, string> = {
  water: 'Eau',
  electricity: 'Électricité',
  both: 'Eau & Électricité',
};

export const mockDossiers: Dossier[] = [
  {
    id: '1',
    reference: 'DOS-2024-001',
    customer: {
      id: 'c1',
      firstName: 'Jean',
      lastName: 'Martin',
      email: 'jean.martin@email.fr',
      phone: '06 12 34 56 78',
      nationalId: '1234567890123',
      address: {
        street: '15 Rue de la République',
        city: 'Lyon',
        postalCode: '69001',
        region: 'Auvergne-Rhône-Alpes',
      },
    },
    subscriptionType: 'both',
    status: 'TECHNICAL_REVIEW',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-18'),
    assignedTo: 'Pierre Durand',
    documents: [],
    statusHistory: [
      { id: 'h1', status: 'DRAFT', timestamp: new Date('2024-01-15'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h2', status: 'DOSSIER_COMPLETE', timestamp: new Date('2024-01-16'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h3', status: 'TECHNICAL_REVIEW', timestamp: new Date('2024-01-18'), userId: '2', userName: 'Pierre Durand' },
    ],
    worksRequired: false,
  },
  {
    id: '2',
    reference: 'DOS-2024-002',
    customer: {
      id: 'c2',
      firstName: 'Sophie',
      lastName: 'Bernard',
      email: 'sophie.bernard@email.fr',
      phone: '06 98 76 54 32',
      nationalId: '9876543210987',
      address: {
        street: '42 Avenue des Champs',
        city: 'Paris',
        postalCode: '75008',
        region: 'Île-de-France',
      },
    },
    subscriptionType: 'electricity',
    status: 'CONTRACT_SENT',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-20'),
    assignedTo: 'Marie Dupont',
    documents: [],
    statusHistory: [
      { id: 'h4', status: 'DRAFT', timestamp: new Date('2024-01-10'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h5', status: 'DOSSIER_COMPLETE', timestamp: new Date('2024-01-12'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h6', status: 'TECHNICAL_REVIEW', timestamp: new Date('2024-01-14'), userId: '2', userName: 'Pierre Durand' },
      { id: 'h7', status: 'CONTRACT_SENT', timestamp: new Date('2024-01-20'), userId: '1', userName: 'Marie Dupont' },
    ],
    worksRequired: false,
  },
  {
    id: '3',
    reference: 'DOS-2024-003',
    customer: {
      id: 'c3',
      firstName: 'Marc',
      lastName: 'Petit',
      email: 'marc.petit@email.fr',
      phone: '06 55 44 33 22',
      nationalId: '5544332211009',
      address: {
        street: '8 Boulevard Victor Hugo',
        city: 'Marseille',
        postalCode: '13001',
        region: 'Provence-Alpes-Côte d\'Azur',
      },
    },
    subscriptionType: 'water',
    status: 'WORKS_REQUIRED',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-19'),
    assignedTo: 'Thomas Leroy',
    documents: [],
    statusHistory: [
      { id: 'h8', status: 'DRAFT', timestamp: new Date('2024-01-08'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h9', status: 'DOSSIER_COMPLETE', timestamp: new Date('2024-01-10'), userId: '1', userName: 'Marie Dupont' },
      { id: 'h10', status: 'TECHNICAL_REVIEW', timestamp: new Date('2024-01-15'), userId: '3', userName: 'Thomas Leroy' },
      { id: 'h11', status: 'WORKS_REQUIRED', timestamp: new Date('2024-01-19'), userId: '3', userName: 'Thomas Leroy', comment: 'Extension du réseau nécessaire' },
    ],
    worksRequired: true,
    quotationAmount: 2500,
  },
  {
    id: '4',
    reference: 'DOS-2024-004',
    customer: {
      id: 'c4',
      firstName: 'Claire',
      lastName: 'Rousseau',
      email: 'claire.rousseau@email.fr',
      phone: '06 11 22 33 44',
      nationalId: '1122334455667',
      address: {
        street: '25 Rue du Commerce',
        city: 'Bordeaux',
        postalCode: '33000',
        region: 'Nouvelle-Aquitaine',
      },
    },
    subscriptionType: 'both',
    status: 'SUBSCRIPTION_ACTIVE',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-05'),
    documents: [],
    statusHistory: [],
    worksRequired: false,
    meterNumber: 'MTR-2024-0042',
  },
  {
    id: '5',
    reference: 'DOS-2024-005',
    customer: {
      id: 'c5',
      firstName: 'Luc',
      lastName: 'Moreau',
      email: 'luc.moreau@email.fr',
      phone: '06 77 88 99 00',
      nationalId: '7788990011223',
      address: {
        street: '12 Place de la Mairie',
        city: 'Toulouse',
        postalCode: '31000',
        region: 'Occitanie',
      },
    },
    subscriptionType: 'electricity',
    status: 'DRAFT',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    documents: [],
    statusHistory: [
      { id: 'h12', status: 'DRAFT', timestamp: new Date('2024-01-20'), userId: '1', userName: 'Marie Dupont' },
    ],
    worksRequired: false,
  },
];

export const mockStats: DashboardStats = {
  totalDossiers: 156,
  activeDossiers: 42,
  pendingReview: 15,
  completedThisMonth: 23,
  averageProcessingDays: 12,
  byStatus: {
    DRAFT: 8,
    DOSSIER_COMPLETE: 5,
    TECHNICAL_REVIEW: 12,
    WORKS_REQUIRED: 6,
    WORKS_VALIDATED: 4,
    CONTRACT_SENT: 8,
    CONTRACT_SIGNED: 5,
    METER_SCHEDULED: 3,
    METER_INSTALLED: 4,
    INSTALLATION_REPORT_RECEIVED: 2,
    CUSTOMER_VALIDATED: 3,
    SUBSCRIPTION_ACTIVE: 92,
    REJECTED: 3,
    CANCELLED: 1,
  },
  byType: {
    water: 45,
    electricity: 68,
    both: 43,
  },
};
